// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkOho0_sNedZ_hoikxDEmBabaQJhfZoQU',
    appId: '1:402674820894:web:cae70b07f25e4001c20b0f',
    messagingSenderId: '402674820894',
    projectId: 'webportof',
    authDomain: 'webportof.firebaseapp.com',
    storageBucket: 'webportof.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA2mFj03reyjYHHaORvSg4Db6eomSnTvCw',
    appId: '1:402674820894:android:1c6298d91c3d00ffc20b0f',
    messagingSenderId: '402674820894',
    projectId: 'webportof',
    storageBucket: 'webportof.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1bF7Ev6VNXq8x8be_kz4h8TT9J7AYuec',
    appId: '1:402674820894:ios:8cb2f92a77c51ff2c20b0f',
    messagingSenderId: '402674820894',
    projectId: 'webportof',
    storageBucket: 'webportof.appspot.com',
    iosClientId: '402674820894-dup78dfebh5pt0se7arhepff4auj68mu.apps.googleusercontent.com',
    iosBundleId: 'com.example.portof',
  );
}
